services:
  web:
    environment:
      - MINIO_REGION=eu-central-1
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=HPEx28w4J4Ez2OD1E3AW
      - MINIO_SECRET_KEY=1x3y42gsnEMuJnz94BErmV6oJp5Q0HlKIpHnxZ6V
  whatsapp-api:
    environment:
      - MINIO_REGION=eu-central-1
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=HPEx28w4J4Ez2OD1E3AW
      - MINIO_SECRET_KEY=1x3y42gsnEMuJnz94BErmV6oJp5Q0HlKIpHnxZ6V
